service: hello

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'} # The stage of the service. Default: dev
  region: us-east-1
  timeout: 60 # The amount of time that Lambda allows a function to run before stopping it.
custom:
  defaultStage: dev
  profiles:
    dev: dev
    prod: prod

package:
  artifact: lambda.zip

functions:
  main:
    handler: hello/main.handler
